spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    username: sa
    url: jdbc:h2:mem:appdb
  h2:
    console:
      enabled: true
      path: /h2-console
